name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Security & Policy Gates (placeholder)
        run: |
          echo "[F8] secrets/SAST/SCA would run here"
          echo "Using ci/gates_config.yaml for gates"
          test -f ci/gates_config.yaml
      - name: Docs-Sync (placeholder)
        run: |
          echo "Docs sync checks would run here"
